# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-02 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=230)),
                ('email', models.EmailField(max_length=254)),
                ('stripe_id', models.CharField(max_length=230)),
            ],
        ),
    ]
